// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxVzad_VDp8yITfcpcUlE4ptmqzIA960',
    appId: '1:124350956970:web:561bb926ca2a9b6e14d7d3',
    messagingSenderId: '124350956970',
    projectId: 'businga-a9756',
    authDomain: 'businga-a9756.firebaseapp.com',
    storageBucket: 'businga-a9756.appspot.com',
    measurementId: 'G-QXKM9HFMWH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlt_f_2jk5PO-fdWcyrgRgi1OLUptRZ6Q',
    appId: '1:124350956970:ios:8ff1bd4fdbfccaaf14d7d3',
    messagingSenderId: '124350956970',
    projectId: 'businga-a9756',
    storageBucket: 'businga-a9756.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlt_f_2jk5PO-fdWcyrgRgi1OLUptRZ6Q',
    appId: '1:124350956970:ios:8ff1bd4fdbfccaaf14d7d3',
    messagingSenderId: '124350956970',
    projectId: 'businga-a9756',
    storageBucket: 'businga-a9756.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhxVzad_VDp8yITfcpcUlE4ptmqzIA960',
    appId: '1:124350956970:web:d706341e132770bc14d7d3',
    messagingSenderId: '124350956970',
    projectId: 'businga-a9756',
    authDomain: 'businga-a9756.firebaseapp.com',
    storageBucket: 'businga-a9756.appspot.com',
    measurementId: 'G-RYYEKB41Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZMLJUH2SGoEPugwQ4uQsGulSDcqd7myM',
    appId: '1:124350956970:android:44f6bfe6414849ce14d7d3',
    messagingSenderId: '124350956970',
    projectId: 'businga-a9756',
    storageBucket: 'businga-a9756.appspot.com',
  );

}